//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("GarconModel", "FK_OrderItem_Order", "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GarconLibrary.DBFramework.Order), "OrderItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GarconLibrary.DBFramework.OrderItem), true)]
[assembly: EdmRelationshipAttribute("GarconModel", "FK_OrderItem_MenuItem", "MenuItem", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GarconLibrary.DBFramework.MenuItem), "OrderItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GarconLibrary.DBFramework.OrderItem), true)]
[assembly: EdmRelationshipAttribute("GarconModel", "FK_Order_Bill", "Bill", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GarconLibrary.DBFramework.Bill), "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GarconLibrary.DBFramework.Order), true)]

#endregion

namespace GarconLibrary.DBFramework
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class GarconEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new GarconEntities object using the connection string found in the 'GarconEntities' section of the application configuration file.
        /// </summary>
        public GarconEntities() : base("name=GarconEntities", "GarconEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GarconEntities object.
        /// </summary>
        public GarconEntities(string connectionString) : base(connectionString, "GarconEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GarconEntities object.
        /// </summary>
        public GarconEntities(EntityConnection connection) : base(connection, "GarconEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MenuItem> MenuItem
        {
            get
            {
                if ((_MenuItem == null))
                {
                    _MenuItem = base.CreateObjectSet<MenuItem>("MenuItem");
                }
                return _MenuItem;
            }
        }
        private ObjectSet<MenuItem> _MenuItem;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order> Order
        {
            get
            {
                if ((_Order == null))
                {
                    _Order = base.CreateObjectSet<Order>("Order");
                }
                return _Order;
            }
        }
        private ObjectSet<Order> _Order;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderItem> OrderItem
        {
            get
            {
                if ((_OrderItem == null))
                {
                    _OrderItem = base.CreateObjectSet<OrderItem>("OrderItem");
                }
                return _OrderItem;
            }
        }
        private ObjectSet<OrderItem> _OrderItem;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bill> Bill
        {
            get
            {
                if ((_Bill == null))
                {
                    _Bill = base.CreateObjectSet<Bill>("Bill");
                }
                return _Bill;
            }
        }
        private ObjectSet<Bill> _Bill;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MenuItem EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMenuItem(MenuItem menuItem)
        {
            base.AddObject("MenuItem", menuItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Order EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrder(Order order)
        {
            base.AddObject("Order", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderItem EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderItem(OrderItem orderItem)
        {
            base.AddObject("OrderItem", orderItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bill EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBill(Bill bill)
        {
            base.AddObject("Bill", bill);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GarconModel", Name="Bill")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bill : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bill object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="totalPrice">Initial value of the TotalPrice property.</param>
        /// <param name="billDate">Initial value of the BillDate property.</param>
        public static Bill CreateBill(global::System.Int32 id, global::System.Decimal totalPrice, global::System.DateTime billDate)
        {
            Bill bill = new Bill();
            bill.Id = id;
            bill.TotalPrice = totalPrice;
            bill.BillDate = billDate;
            return bill;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TotalPrice
        {
            get
            {
                return _TotalPrice;
            }
            set
            {
                OnTotalPriceChanging(value);
                ReportPropertyChanging("TotalPrice");
                _TotalPrice = StructuralObject.SetValidValue(value, "TotalPrice");
                ReportPropertyChanged("TotalPrice");
                OnTotalPriceChanged();
            }
        }
        private global::System.Decimal _TotalPrice;
        partial void OnTotalPriceChanging(global::System.Decimal value);
        partial void OnTotalPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime BillDate
        {
            get
            {
                return _BillDate;
            }
            set
            {
                OnBillDateChanging(value);
                ReportPropertyChanging("BillDate");
                _BillDate = StructuralObject.SetValidValue(value, "BillDate");
                ReportPropertyChanged("BillDate");
                OnBillDateChanged();
            }
        }
        private global::System.DateTime _BillDate;
        partial void OnBillDateChanging(global::System.DateTime value);
        partial void OnBillDateChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GarconModel", Name="MenuItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MenuItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MenuItem object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="menuItemCategoryId">Initial value of the MenuItemCategoryId property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        /// <param name="cookingTimeMinutes">Initial value of the CookingTimeMinutes property.</param>
        /// <param name="prepTimeMinutes">Initial value of the PrepTimeMinutes property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        /// <param name="isChefRecommended">Initial value of the IsChefRecommended property.</param>
        public static MenuItem CreateMenuItem(global::System.Int32 id, global::System.String name, global::System.Int32 menuItemCategoryId, global::System.Decimal price, global::System.Int32 cookingTimeMinutes, global::System.Int32 prepTimeMinutes, global::System.Boolean isActive, global::System.Boolean isChefRecommended)
        {
            MenuItem menuItem = new MenuItem();
            menuItem.Id = id;
            menuItem.Name = name;
            menuItem.MenuItemCategoryId = menuItemCategoryId;
            menuItem.Price = price;
            menuItem.CookingTimeMinutes = cookingTimeMinutes;
            menuItem.PrepTimeMinutes = prepTimeMinutes;
            menuItem.IsActive = isActive;
            menuItem.IsChefRecommended = isChefRecommended;
            return menuItem;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MenuItemCategoryId
        {
            get
            {
                return _MenuItemCategoryId;
            }
            set
            {
                OnMenuItemCategoryIdChanging(value);
                ReportPropertyChanging("MenuItemCategoryId");
                _MenuItemCategoryId = StructuralObject.SetValidValue(value, "MenuItemCategoryId");
                ReportPropertyChanged("MenuItemCategoryId");
                OnMenuItemCategoryIdChanged();
            }
        }
        private global::System.Int32 _MenuItemCategoryId;
        partial void OnMenuItemCategoryIdChanging(global::System.Int32 value);
        partial void OnMenuItemCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value, "Price");
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Decimal _Price;
        partial void OnPriceChanging(global::System.Decimal value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CookingTimeMinutes
        {
            get
            {
                return _CookingTimeMinutes;
            }
            set
            {
                OnCookingTimeMinutesChanging(value);
                ReportPropertyChanging("CookingTimeMinutes");
                _CookingTimeMinutes = StructuralObject.SetValidValue(value, "CookingTimeMinutes");
                ReportPropertyChanged("CookingTimeMinutes");
                OnCookingTimeMinutesChanged();
            }
        }
        private global::System.Int32 _CookingTimeMinutes;
        partial void OnCookingTimeMinutesChanging(global::System.Int32 value);
        partial void OnCookingTimeMinutesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PrepTimeMinutes
        {
            get
            {
                return _PrepTimeMinutes;
            }
            set
            {
                OnPrepTimeMinutesChanging(value);
                ReportPropertyChanging("PrepTimeMinutes");
                _PrepTimeMinutes = StructuralObject.SetValidValue(value, "PrepTimeMinutes");
                ReportPropertyChanged("PrepTimeMinutes");
                OnPrepTimeMinutesChanged();
            }
        }
        private global::System.Int32 _PrepTimeMinutes;
        partial void OnPrepTimeMinutesChanging(global::System.Int32 value);
        partial void OnPrepTimeMinutesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value, "IsActive");
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsChefRecommended
        {
            get
            {
                return _IsChefRecommended;
            }
            set
            {
                OnIsChefRecommendedChanging(value);
                ReportPropertyChanging("IsChefRecommended");
                _IsChefRecommended = StructuralObject.SetValidValue(value, "IsChefRecommended");
                ReportPropertyChanged("IsChefRecommended");
                OnIsChefRecommendedChanged();
            }
        }
        private global::System.Boolean _IsChefRecommended;
        partial void OnIsChefRecommendedChanging(global::System.Boolean value);
        partial void OnIsChefRecommendedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageLink
        {
            get
            {
                return _ImageLink;
            }
            set
            {
                OnImageLinkChanging(value);
                ReportPropertyChanging("ImageLink");
                _ImageLink = StructuralObject.SetValidValue(value, true, "ImageLink");
                ReportPropertyChanged("ImageLink");
                OnImageLinkChanged();
            }
        }
        private global::System.String _ImageLink;
        partial void OnImageLinkChanging(global::System.String value);
        partial void OnImageLinkChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GarconModel", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="orderDate">Initial value of the OrderDate property.</param>
        /// <param name="serviceCharge">Initial value of the ServiceCharge property.</param>
        /// <param name="inclusiveTax">Initial value of the InclusiveTax property.</param>
        /// <param name="orderStatusId">Initial value of the OrderStatusId property.</param>
        public static Order CreateOrder(global::System.Int32 id, global::System.DateTime orderDate, global::System.Decimal serviceCharge, global::System.Decimal inclusiveTax, global::System.Int32 orderStatusId)
        {
            Order order = new Order();
            order.Id = id;
            order.OrderDate = orderDate;
            order.ServiceCharge = serviceCharge;
            order.InclusiveTax = inclusiveTax;
            order.OrderStatusId = orderStatusId;
            return order;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                OnOrderDateChanging(value);
                ReportPropertyChanging("OrderDate");
                _OrderDate = StructuralObject.SetValidValue(value, "OrderDate");
                ReportPropertyChanged("OrderDate");
                OnOrderDateChanged();
            }
        }
        private global::System.DateTime _OrderDate;
        partial void OnOrderDateChanging(global::System.DateTime value);
        partial void OnOrderDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ServiceCharge
        {
            get
            {
                return _ServiceCharge;
            }
            set
            {
                OnServiceChargeChanging(value);
                ReportPropertyChanging("ServiceCharge");
                _ServiceCharge = StructuralObject.SetValidValue(value, "ServiceCharge");
                ReportPropertyChanged("ServiceCharge");
                OnServiceChargeChanged();
            }
        }
        private global::System.Decimal _ServiceCharge;
        partial void OnServiceChargeChanging(global::System.Decimal value);
        partial void OnServiceChargeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal InclusiveTax
        {
            get
            {
                return _InclusiveTax;
            }
            set
            {
                OnInclusiveTaxChanging(value);
                ReportPropertyChanging("InclusiveTax");
                _InclusiveTax = StructuralObject.SetValidValue(value, "InclusiveTax");
                ReportPropertyChanged("InclusiveTax");
                OnInclusiveTaxChanged();
            }
        }
        private global::System.Decimal _InclusiveTax;
        partial void OnInclusiveTaxChanging(global::System.Decimal value);
        partial void OnInclusiveTaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BillId
        {
            get
            {
                return _BillId;
            }
            set
            {
                OnBillIdChanging(value);
                ReportPropertyChanging("BillId");
                _BillId = StructuralObject.SetValidValue(value, "BillId");
                ReportPropertyChanged("BillId");
                OnBillIdChanged();
            }
        }
        private Nullable<global::System.Int32> _BillId;
        partial void OnBillIdChanging(Nullable<global::System.Int32> value);
        partial void OnBillIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderStatusId
        {
            get
            {
                return _OrderStatusId;
            }
            set
            {
                OnOrderStatusIdChanging(value);
                ReportPropertyChanging("OrderStatusId");
                _OrderStatusId = StructuralObject.SetValidValue(value, "OrderStatusId");
                ReportPropertyChanged("OrderStatusId");
                OnOrderStatusIdChanged();
            }
        }
        private global::System.Int32 _OrderStatusId;
        partial void OnOrderStatusIdChanging(global::System.Int32 value);
        partial void OnOrderStatusIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GarconModel", "FK_Order_Bill", "Bill")]
        public Bill Bill
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bill>("GarconModel.FK_Order_Bill", "Bill").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bill>("GarconModel.FK_Order_Bill", "Bill").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bill> BillReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bill>("GarconModel.FK_Order_Bill", "Bill");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bill>("GarconModel.FK_Order_Bill", "Bill", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GarconModel", "FK_OrderItem_Order", "OrderItem")]
        public EntityCollection<OrderItem> OrderItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderItem>("GarconModel.FK_OrderItem_Order", "OrderItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderItem>("GarconModel.FK_OrderItem_Order", "OrderItem", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GarconModel", Name="OrderItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderItem object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="orderId">Initial value of the OrderId property.</param>
        /// <param name="orderItemStatusId">Initial value of the OrderItemStatusId property.</param>
        /// <param name="menuItemId">Initial value of the MenuItemId property.</param>
        /// <param name="quantity">Initial value of the Quantity property.</param>
        public static OrderItem CreateOrderItem(global::System.Int32 id, global::System.Int32 orderId, global::System.Int32 orderItemStatusId, global::System.Int32 menuItemId, global::System.Int32 quantity)
        {
            OrderItem orderItem = new OrderItem();
            orderItem.Id = id;
            orderItem.OrderId = orderId;
            orderItem.OrderItemStatusId = orderItemStatusId;
            orderItem.MenuItemId = menuItemId;
            orderItem.Quantity = quantity;
            return orderItem;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                OnOrderIdChanging(value);
                ReportPropertyChanging("OrderId");
                _OrderId = StructuralObject.SetValidValue(value, "OrderId");
                ReportPropertyChanged("OrderId");
                OnOrderIdChanged();
            }
        }
        private global::System.Int32 _OrderId;
        partial void OnOrderIdChanging(global::System.Int32 value);
        partial void OnOrderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderItemStatusId
        {
            get
            {
                return _OrderItemStatusId;
            }
            set
            {
                OnOrderItemStatusIdChanging(value);
                ReportPropertyChanging("OrderItemStatusId");
                _OrderItemStatusId = StructuralObject.SetValidValue(value, "OrderItemStatusId");
                ReportPropertyChanged("OrderItemStatusId");
                OnOrderItemStatusIdChanged();
            }
        }
        private global::System.Int32 _OrderItemStatusId;
        partial void OnOrderItemStatusIdChanging(global::System.Int32 value);
        partial void OnOrderItemStatusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MenuItemId
        {
            get
            {
                return _MenuItemId;
            }
            set
            {
                OnMenuItemIdChanging(value);
                ReportPropertyChanging("MenuItemId");
                _MenuItemId = StructuralObject.SetValidValue(value, "MenuItemId");
                ReportPropertyChanged("MenuItemId");
                OnMenuItemIdChanged();
            }
        }
        private global::System.Int32 _MenuItemId;
        partial void OnMenuItemIdChanging(global::System.Int32 value);
        partial void OnMenuItemIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value, "Quantity");
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Int32 _Quantity;
        partial void OnQuantityChanging(global::System.Int32 value);
        partial void OnQuantityChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GarconModel", "FK_OrderItem_Order", "Order")]
        public Order Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("GarconModel.FK_OrderItem_Order", "Order").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("GarconModel.FK_OrderItem_Order", "Order").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Order> OrderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("GarconModel.FK_OrderItem_Order", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Order>("GarconModel.FK_OrderItem_Order", "Order", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GarconModel", "FK_OrderItem_MenuItem", "MenuItem")]
        public MenuItem MenuItem
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MenuItem>("GarconModel.FK_OrderItem_MenuItem", "MenuItem").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MenuItem>("GarconModel.FK_OrderItem_MenuItem", "MenuItem").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MenuItem> MenuItemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MenuItem>("GarconModel.FK_OrderItem_MenuItem", "MenuItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MenuItem>("GarconModel.FK_OrderItem_MenuItem", "MenuItem", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
